#! /usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

if [[ -f hmm.zip ]]; then
  rm hmm.zip
fi

haxe build.hxml
#git add -A
#git commit -m 'Submit to haxelib'

zip -r hmm.zip LICENSE README.md build.hxml haxelib.json hmm run.n src

haxelib submit hmm.zip
