#! /usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Before running this, update the haxelib.json to set the version/releasenote, commit that, then tag it:
# git tag -a 2.3.4 -m "my message"

if [[ -f hmm.zip ]]; then
  rm hmm.zip
fi

haxe build.hxml
#git add -A
#git commit -m 'Submit to haxelib'

zip -r hmm.zip LICENSE README.md build.hxml haxelib.json hmm hmm.cmd run.n src

haxelib submit hmm.zip
